package:
  name: atk
  version: 2.12.0

source:
  fn: atk-2.12.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/atk/2.12/atk-2.12.0.tar.xz
  sha256: 48a8431974639c5a59c24fcd3ece1a19709872d5dfe78907524d9f5e9993f18f

requirements:
  build:
   - glib

  run:
   - glib

about:
  home: http://library.gnome.org/devel/atk/
  license: LGPL
