package:
  name: gdk-pixbuf
  version: 2.30.8

source:
  fn: gdk-pixbuf-2.30.8.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/gdk-pixbuf/2.30/gdk-pixbuf-2.30.8.tar.xz
  sha256: 4853830616113db4435837992c0aebd94cbb993c44dc55063cee7f72a7bef8be

requirements:
  build:
   - glib
   - jpeg
   - libtiff
   - libpng

  run:
   - glib
   - jpeg
   - libtiff
   - libpng

about:
  home: http://gtk.org
  license: LGPL
