package:
  name: landmarkerio-server
  version: 0.0.7

source:
  fn: landmarkerio-server-0.0.7.tar.gz
  url: https://pypi.python.org/packages/source/l/landmarkerio-server/landmarkerio-server-0.0.7.tar.gz
  md5: 7a01e404731347461b4ad230f3322989

requirements:
  build:
    - python
    - setuptools
    - flask
    - flask-restful
    - flask-compress
    - menpo

  run:
    - python
    - flask
    - flask-restful
    - flask-compress
    - menpo

test:
  imports:
    - landmarkerioserver

about:
  home: https://github.com/menpo/landmarkerio-server
  license: BSD
