package:
  name: landmarkerio-server
  version: 0.0.6

source:
  fn: landmarkerio-server-0.0.6.tar.gz
  url: https://pypi.python.org/packages/source/l/landmarkerio-server/landmarkerio-server-0.0.6.tar.gz
  md5: d9f6b72a1d8b6a211001513bfdddccdb

requirements:
  build:
    - python
    - setuptools
    - flask
    - flask-restful
    - menpo

  run:
    - python
    - flask
    - flask-restful
    - menpo

test:
  imports:
    - landmarkerioserver

about:
  home: https://github.com/menpo/landmarkerio-server
  license: BSD
