package:
  name: iconv
  version: "1.14"

# REQUIRES 7ZIP
source:
    fn:  iconv-1.14-win32-x86.7z  # [win32]
    url: ftp://ftp.zlatkovic.com/libxml/64bit/iconv-1.14-win32-x86.7z  # [win32]
    fn:  iconv-1.14-win32-x86_64.7z  # [win64]
    url: ftp://ftp.zlatkovic.com/libxml/64bit/iconv-1.14-win32-x86_64.7z  # [win64]

about:
  # Taken from here
  home: http://www.zlatkovic.com/libxml.en.html
  license: MIT
