package:
  name: scikits.sparse
  version: "0.2"

source:
  fn: scikits.sparse-0.2.zip
  url: https://github.com/njsmith/scikits-sparse/archive/2fd1533b847b1cea82b2143ac334d770a26fa2a3.zip

requirements:
  build:
    - python
    - setuptools
    - scipy
    - cython
    - numpy >=1.9
    - suitesparse 4.4.1

  run:
    - python
    - setuptools
    - scipy
    - numpy >=1.9
    - suitesparse 4.4.1

test:
  imports:
    - scikits.sparse
    - scikits.sparse.cholmod

  requires:
    - nose

  commands:
    - nosetests scikits.sparse.test_cholmod

about:
  home: https://pythonhosted.org/scikits.sparse
  license: BSD

