package:
  name: glib
  version: 2.40.0

source:
  fn: glib-2.40.0.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/glib/2.40/glib-2.40.0.tar.xz
  sha256: 0d27f195966ecb1995dcce0754129fd66ebe820c7cd29200d264b02af1aa28b5

requirements:
  build:
   - python
   - libffi
   - gettext

  run:
   - python
   - libffi
   - gettext

about:
  home: http://developer.gnome.org/glib/
  license: LGPL
