package:
  name: pango
  version: 1.34.1

source:
  fn: pango-1.34.1.tar.xz
  url: http://ftp.gnome.org/pub/GNOME/sources/pango/1.34/pango-1.34.1.tar.xz
  sha256: 1aea30df34a8ae4fcce71afd22aa5b57224b52916d46e3ea81ff9f1eb130e64c

requirements:
  build:
   - glib
   - cairo
   - harfbuzz

  run:
   - glib
   - cairo
   - harfbuzz

about:
  home: http://www.pango.org/
  license: LGPL
