package:
  name: cyassimp
  version: 0.1.3

source:
  fn: cyassimp-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/c/cyassimp/cyassimp-0.1.3.tar.gz
  md5: a0cded25388b7ae903841266420ec3ff

  patches:
    - windows_setup.patch

requirements:
  build:
    - python
    - distribute
    - numpy
    - cython
    - assimp

  run:
    - python
    - numpy
	
test:
  imports:
    - cyassimp

about:
  home: https://github.com/menpo/cyassimp/
  license: BSD License
