package:
  name: cyassimp
  version: "0.1.3"

source:
  fn: cyassimp-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/c/cyassimp/cyassimp-0.1.3.tar.gz
  md5: a0cded25388b7ae903841266420ec3ff

  patches:
    - windows_setup.patch [win]

build:
  number: 1

requirements:
  build:
    - python
    - distribute
    - numpy 1.8.0
    - cython 0.20.1
    - assimp 3.0.1270

  run:
    - python
    - numpy 1.8.0
    - assimp 3.0.1270  # [unix]
	
test:
  imports:
    - cyassimp

about:
  home: https://github.com/menpo/cyassimp/
  license: BSD License
