package:
  name: gettext
  version: 0.18.3.2

source:
  fn: gettext-0.18.3.2.tar.gz
  url: http://ftpmirror.gnu.org/gettext/gettext-0.18.3.2.tar.gz
  sha256: d1a4e452d60eb407ab0305976529a45c18124bd518d976971ac6dc7aa8b4c5d7

about:
  home: http://www.gnu.org/software/gettext/
  license: LGPL
