package:
  name: cyrasterize
  version: "0.1.5"

source:
  fn: cyrasterize-0.1.5.tar.gz
  url: https://pypi.python.org/packages/source/c/cyrasterize/cyrasterize-0.1.5.tar.gz
  md5: 33dcc76dbeb639112c7936711122ec2f

  patches:
    - windows_setup.patch [win]
	
build:
  number: 1

requirements:
  build:
    - python
    - distribute
    - numpy 1.8.0
    - cython 0.20.1
    - glew 1.10.0
    - glfw3 3.0.4
    - msinttypes r26  # [win]

  run:
    - python
    - numpy 1.8.0
    - glew 1.10.0  # [unix]
    - glfw3 3.0.4  # [unix]
    
test:
  imports:
    - cyrasterize

about:
  home: https://github.com/menpo/cyrasterize/
  license: BSD
