package:
  name: cyrasterize
  version: 0.1.4

source:
  fn: cyrasterize-0.1.4.zip
  url: https://github.com/menpo/cyrasterize/archive/windows_fixes.zip
  #url: https://pypi.python.org/packages/source/c/cyrasterize/cyrasterize-0.1.4.tar.gz
  #md5: 67e5cd526c60833c37f67f31e1d63481

  patches:
    - windows_setup.patch

requirements:
  build:
    - python
    - distribute
    - numpy
    - cython
    - glew
    - glfw3
    - msinttypes

  run:
    - python
    - numpy
    
test:
  imports:
    - cyrasterize

about:
  home: https://github.com/menpo/cyrasterize/
  license: BSD
