package:
  name: menpo-pyvrml97
  version: 2.3.0a4

source:
  fn: menpo-pyvrml97-2.3.0a4.tar.gz
  url: https://pypi.python.org/packages/source/m/menpo-PyVRML97/menpo-PyVRML97-2.3.0a4.tar.gz
  md5: 07d28598ca55c4b71d4e44692627f3db
  
build:
  number: 1

requirements:
  build:
    - python
    - numpy 1.8.0
    - setuptools
    - simpleparse 2.1.1
    - pydispatcher 2.0.3

  run:
    - python
    - numpy 1.8.0
    - simpleparse 2.1.1
    - pydispatcher 2.0.3

test:
  imports:
    - vrml.vrml97.parser

about:
  home: https://github.com/menpo/vrml97/
  license: BSD
