package:
  name: ceres-solver
  version: "1.9.0"

source:
  fn: ceres-solver-1.9.0.tar.gz
  url: http://ceres-solver.org/ceres-solver-1.9.0.tar.gz
  sha1: f73ab69cfa1e19d40961503984bc7d6b601cb8a6

requirements:
  build:
    - cmake [win]
    - suitesparse
    - eigen
    - tbb

  run:
   - suitesparse
   - eigen
   - tbb

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
