package:
  name: ceres-solver
  version: "1.10.0rc1"

source:
  fn: ceres-solver-1.10.0rc1.tar.gz
  url: https://ceres-solver.googlesource.com/ceres-solver/+archive/6768b3586a027bb850c0a50e2a27380f5d80142a.tar.gz


requirements:
  build:
    - cmake [win]
    - suitesparse
    - eigen
    - tbb

  run:
   - suitesparse
   - eigen
   - tbb

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
