package:
  name: libxml2
  version: "2.7.8"

# REQUIRES 7ZIP
source:
    fn:  libxml2-2.7.8.win32.zip  # [win32]
    url: ftp://ftp.zlatkovic.com/libxml/libxml2-2.7.8.win32.zip  # [win32]
    fn:  libxml2-2.9.2-win32-x86_64.7z  # [win64]
    url: ftp://ftp.zlatkovic.com/libxml/64bit/libxml2-2.9.2-win32-x86_64.7z  # [win64]


requirements:
  run:
    - zlib 1.2.*
    - iconv 1.14*

about:
  home: http://www.zlatkovic.com/libxml.en.html
  license: MIT
