{% set version = "1.13.0" %}

package:
  name: glew
  version: {{ version }}

source:
  fn: glew-{{ version }}.tgz
  url: http://sourceforge.net/projects/glew/files/glew/snapshots/glew-20151117.tgz/download

  patches:
    - osmesa.patch

requirements:
  build:
    - cmake

about:
  home: http://glew.sourceforge.net/
  license: BSD
