package:
  name: gtk
  version: 2.24.23

source:
  fn: gtk+-2.24.23.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/gtk+/2.24/gtk+-2.24.23.tar.xz
  sha256: a0a406e27e9b5e7d6b2c4334212706ed5cdcd41e713e66c9ae950655dd61517c

requirements:
  build:
   - glib
   - jpeg
   - libtiff
   - gdk-pixbuf
   - pango
   - atk
   - cairo

  run:
   - glib
   - jpeg
   - libtiff
   - gdk-pixbuf
   - pango
   - atk
   - cairo

about:
  home: http://gtk.org/
  license: LGPL
