package:
  name: menpo
  version: 0.2

source:
  fn: menpo-0.2.zip
  url: https://github.com/menpo/menpo/archive/windows_fixes.zip
  #url: https://pypi.python.org/packages/source/c/cyrasterize/cyrasterize-0.1.4.tar.gz
  #md5: 67e5cd526c60833c37f67f31e1d63481

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython

  run:
    - python
    - numpy
    - scipy
    - cyrasterize
    - cyassimp
    - pillow
    - mayavi
    - scikit-image
    - scikit-learn
    - matplotlib
    - decorator
    - ipython-notebook
    - menpo-pyvrml97

test:
  imports:
    - menpo.decomposition
    - menpo.features
    - menpo.fit
    - menpo.fitmultilevel
    - menpo.groupalign
    - menpo.image
    - menpo.interpolation
    - menpo.io
    - menpo.landmark
    - menpo.model
    - menpo.rasterize
    - menpo.shape
    - menpo.transform
    - menpo.visualize

about:
  home: https://github.com/menpo/menpo/
  license: BSD
