package:
  name: menpo
  version: 0.3.0

source:
  fn: menpo-0.3.0.tar.gz
  url: https://pypi.python.org/packages/source/m/menpo/menpo-0.3.0.tar.gz
  md5: 2d1b9da715a4fe934ca08682260bab98

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython

  run:
    - python
    - numpy
    - scipy
    - cyrasterize
    - cyassimp
    - imaging
    - mayavi
    - scikit-image
    - scikit-learn
    - matplotlib
    - decorator
    - ipython-notebook
    - menpo-pyvrml97
    - cython
    - nose
    - pathlib
    - pip

test:
  imports:
    - menpo.fit
    - menpo.fitmultilevel
    - menpo.image
    - menpo.io
    - menpo.landmark
    - menpo.model
    - menpo.rasterize
    - menpo.shape
    - menpo.transform
    - menpo.visualize

about:
  home: https://github.com/menpo/menpo/
  license: BSD
