package:
  name: menpo
  version: "0.3.0"

source:
  fn: menpo-0.3.0.tar.gz
  url: https://pypi.python.org/packages/source/m/menpo/menpo-0.3.0.tar.gz
  md5: 2d1b9da715a4fe934ca08682260bab98
  
build:
  number: 1

requirements:
  build:
    - python
    - setuptools 
    - numpy 1.8.0
    - cython 0.20.1

  run:
    - python
    - numpy 1.8.0
    - scipy 0.14.0
    - cyrasterize 0.1.5
    - cyassimp 0.1.3
    - pillow 2.5.1
    - mayavi 4.3.1
    - scikit-image 0.9.3
    - scikit-learn 0.14.1
    - matplotlib 1.3.1
    - decorator 3.4.0
    - ipython-notebook 
    - menpo-pyvrml97 2.3.0a4
    - cython 0.20.1
    - nose 
    - pathlib 1.0
    - pip

test:
  imports:
    - menpo.fit
    - menpo.fitmultilevel
    - menpo.image
    - menpo.io
    - menpo.landmark
    - menpo.model
    - menpo.rasterize
    - menpo.shape
    - menpo.transform
    - menpo.visualize

about:
  home: https://github.com/menpo/menpo/
  license: BSD
