package:
  name: menpo
  version: 0.2.1

source:
  fn: menpo-0.2.1.tar.gz
  url: https://pypi.python.org/packages/source/m/menpo/menpo-0.2.1.tar.gz
  md5: 031c0a8677e74e6ed21f3c335b93988f

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython

  run:
    - python
    - numpy
    - scipy
    - cyrasterize
    - cyassimp
    - pillow
    - mayavi
    - scikit-image
    - scikit-learn
    - matplotlib
    - decorator
    - ipython-notebook
    - menpo-pyvrml97

test:
  imports:
    - menpo.decomposition
    - menpo.features
    - menpo.fit
    - menpo.fitmultilevel
    - menpo.groupalign
    - menpo.image
    - menpo.interpolation
    - menpo.io
    - menpo.landmark
    - menpo.model
    - menpo.rasterize
    - menpo.shape
    - menpo.transform
    - menpo.visualize

about:
  home: https://github.com/menpo/menpo/
  license: BSD
