package:
  name: pystan
  version: 2.3.0.0

source:
  fn: pystan-2.3.0.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pystan/pystan-2.3.0.0.tar.gz
  md5: 0cda5e22bfe878c8ebe4cdc1aaf671c7
  
  patches:
    - windows_setup.patch [win]

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - msinttypes [win]

  run:
    - python
    - numpy
    - cython

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/pystan.html
  license: GPLv3
