package:
  name: pystan
  version: 2.4.0.3

source:
  fn: pystan-2.4.0.3.tar.gz
  url: https://pypi.python.org/packages/source/p/pystan/pystan-2.4.0.3.tar.gz
  md5: 535a65e44b59430153134d1d802683e5
  
  patches:
    - windows_setup.patch [win]

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - msinttypes [win]

  run:
    - python
    - numpy
    - cython

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/pystan.html
  license: GPLv3
