package:
  name: pystan
  version: "2.7.0.0"

source:
  fn: pystan-2.7.0.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pystan/pystan-2.7.0.0.tar.gz
  md5: 96b956db18393dc71534c60d6e6e6edd
  
  patches:
    - windows_setup.patch  # [win]
    - msvc_2008_math.patch  # [win]

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - msinttypes  # [win]

  run:
    - python
    - numpy
    - cython

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/pystan.html
  license: GPLv3
