package:
  name: pystan
  version: "2.5.0.1"

source:
  fn: pystan-2.5.0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pystan/pystan-2.5.0.1.tar.gz
  md5: b53ba804147338288fce0f23da428871
  
  patches:
    - windows_setup.patch [win]

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - msinttypes [win]

  run:
    - python
    - numpy
    - cython

test:
  imports:
    - pystan

about:
  home: http://mc-stan.org/pystan.html
  license: GPLv3
