package:
  name: opencv
  version: 2.4.11

source:
  fn: opencv-2.4.11.zip
  url: http://sourceforge.net/projects/opencvlibrary/files/opencv-unix/2.4.11/opencv-2.4.11.zip/download
  sha1: d6e3048416d42213c204f89b9dfe39742f9a708c

requirements:
  build:
   - cmake  # [win]
   - numpy
   - eigen
   - tbb  # [osx]

  run:
   - python
   - numpy
   - tbb  # [osx]

test:
  imports:
    - cv2
    - cv2.cv

about:
  home: http://opencv.org/
  license: BSD
