package:
  name: pathlib
  version: 1.0

source:
  fn: pathlib-1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pathlib/pathlib-1.0.tar.gz
  md5: a0a834e2ac9e280f9cfc3a06f5ac1ca3

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pathlib

about:
  home: https://pathlib.readthedocs.org/
  license: MIT

