package:
  name: boost
  version: 1.55.0

source:
  fn: boost_1_55_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download
  md5: d6eef4b4cacb2183f2bf265a5a03a354

requirements:
  build:
    - python
    - bzip2

  run:
    - python
    - bzip2

about:
  home: http://www.boost.org/
  license: Boost Software License
