package:
  name: boost_python
  version: 1.55.0

source:
  fn: boost_1_55_0.tar.gz
  url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.gz/download
  md5: 93780777cfbf999a600f62883bd54b17

about:
  home: http://www.boost.org/
  license: Boost Software License
