package:
  name: boost
  version: 1.56.0

source:
  fn: boost_1_56_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.56.0/boost_1_56_0.tar.bz2/download
  sha1: f94bb008900ed5ba1994a1072140590784b9b5df

requirements:
  build:
    - python
    - bzip2

  run:
    - python
    - bzip2

about:
  home: http://www.boost.org/
  license: Boost Software License
