package:
  name: dlib
  version: "18.13"

source:
  fn: dlib-18.13.tar.bz2
  url: http://sourceforge.net/projects/dclib/files/dlib/v18.13/dlib-18.13.tar.bz2/download
  sha1: e65cb01a263bd30c1edfd3dcef36d26596f6e551
  
build:
  number: 0

requirements:
  build:
   - python
   - cmake  # [win]
   - boost
   - jpeg
   - libpng
   - sqlite

  run:
   - python
   - boost
   - jpeg
   - libpng
   - sqlite

test:
  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost Software License
