package:
  name: dlib
  version: "18.10"

source:
  fn: dlib-18.10.tar.bz2
  url: http://sourceforge.net/projects/dclib/files/dlib/v18.10/dlib-18.10.tar.bz2/download
  sha1: 8010cd5c173277d7327135f75f3565d15491592e
  
  patches:
   - gui_patch.patch
requirements:
  build:
   - python
   - cmake  # [win]
   - boost_python
   - jpeg
   - libpng
   - sqlite

  run:
   - python
   - boost_python
   - jpeg
   - libpng
   - sqlite

test:
  imports:
    - dlib

about:
  home: http://dlib.net/
  license: Boost Software License
