package:
  name: harfbuzz
  version: 0.9.29

source:
  fn: harfbuzz-0.9.29.tar.bz2
  url: http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-0.9.29.tar.bz2
  sha256: 601cea38c6fa0cf362dd9042c66cf4db711c5f9390de4ca46d6d2fc3f64de390

requirements:
  build:
   - glib
   - cairo

  run:
   - glib
   - cairo

about:
  home: http://www.freedesktop.org/wiki/Software/HarfBuzz
  license: LGPL
