package:
  name: cmake
  version: 3.3.0

source:
  fn: cmake-3.3.0.zip [win]
  url: http://www.cmake.org/files/v3.3/cmake-3.3.0.zip [win]
 md5: 402502e7e9a023990bed432667efae3e [win]
  
about:
  home: http://www.cmake.org/
  license: BSD
