package:
  name: aniso8601
  version: 0.82

source:
  fn: aniso8601-0.82.tar.gz
  url: https://pypi.python.org/packages/source/a/aniso8601/aniso8601-0.82.tar.gz
  md5: 044490d60a079d33eb01c19fd469efdb

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - aniso8601

about:
  home: https://bitbucket.org/nielsenb/aniso8601
  license: GPLv3+
